from time import sleep

def whatIsIt():
	print("Hello dear user!")
	sleep(1)
	print("Thanks for download my library!")
	sleep(2)
	print("Homepage on github: https://github.com/GrandTheBest/sfmanager")
	sleep(2)
	print("Issues page on github: https://github.com/GrandTheBest/sfmanager/issues")
	sleep(2)
	print("By this library you can work with text, image and other files.")
	sleep(2)
	print("You can read, set, add and replace content in text files.")
	sleep(2)
	print("Also you can create, copy, move, rename and remove any files.")
	sleep(2)
	print("That's all. Stay tuned!")
	sleep(2)
	print("Thanks for using! Good luck!")
	sleep(1)